### ISSUE TITLE
메인

### ISSUE THREAD

**Issue by kugorang** [KraftonJungle4th/MOTION-BEAT-Frontend#1]
- [x] 플레이 타입 컴포넌트로 변경 후 이동
- [x] 연습모드 컴포넌트로 변경 후 이동
- [x] 랭킹 컴포넌트로 변경 후 이동
- [x] 설정 컴포넌트로 변경 후 이동
- [x] 친구 창 모달 띄우기
- [x] 마이 페이지 모달 띄우기
- [x] 로그인 페이지로 이동 (jwt 토큰 삭제)

**Comment by AnyTHIW** [comment]
1. sticky button의 기능 (친구창, 마이페이지)는 모달이 더 적합해서 바꿨습니다.
2. jwtoken만 삭제하면 되나요? 아니면 다른 데이터도 다 날리는 게 좋나요?
