### ISSUE TITLE
MediaPipe

### ISSUE THREAD

**Issue by kugorang** [KraftonJungle4th/MOTION-BEAT-Frontend#25]
- [x] MediaPipe를 통한 모션 인식
- [x] OpenVidu로 로컬에서 통신 확인
- [x] OpenVidu에서 Mediapipe Pose 적용하기
  - [x] OpenVidu에 내 카메라에 MediaPipe Pose 인식하기.
  - [x] BGM 재생 및 포즈 인식에 맞게 효과음 재생.

**Comment by Indwoo** [comment]
- [ ] OpenVidu로 로컬에서 통신 확인
- [ ] OpenVidu에서 Mediapipe 적용하기

**Comment by kugorang** [comment]
@Indwoo 님과 함께 남은 Task 정리 후 MediaPipe와 OpenVidu 통합 Task를 #24 (실시간 화상공유 (OpenVidu)) Task를 2차 마일스톤으로 이동
