### ISSUE TITLE
대기 방(1차)

### ISSUE THREAD

**Issue by CamelIsTheBestConvention** [KraftonJungle4th/MOTION-BEAT-Frontend#5]
- [x] 방 입장
- [x] 서버가 주는 정보로 방 초기 설정
  - [x] 접속 중인 모든 유저의 socketId, 닉네임, 준비 완료 여부
  - [x] 현재 선택된 곡의 정보 출력
    - [x] 제목
    - [x] 가수
    - [x] 플레이타임
    - [x] 난이도
- [x] 방을 만든 유저의 닉네임을 상단 제목에 표시
- [x] 방장만 시작버튼이 있고 유저들은 대기 중 버튼이 있음
- [x] 방 퇴장
    - [x] 나가기 버튼 클릭 시 나가기 요청
    - [x] 나가기 응답 수신 시 메인페이지로 이동 
- [x] 이미지 클릭 시 노래 선택 모달 진입 요청
- [x] 진입 시 실시간 통신(소켓 사용)
  - [x] 실시간으로 채팅이 구현되는지
  - [x] 노래를 변경하면 전체 유저가 볼 수 있는지
  - [x] 유저가 준비버튼을 누를 때 모든 유저가 볼 수 있는지
- [x] 노래 지정
  - [x] 현재 노래의 정보가 잘 나오는지
  - [x] 노래의 이미지를 클릭 시 노래 선택 모달창이 나오는지
  - [x] 노래 선택하면 노래 정보에 다른 노래로 업데이트가 되는지

**Comment by kugorang** [comment]
* 썸네일, 노래는 S3에 저장
* 2차 마일스톤으로 설정
